kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus3-data
  finalizers:
    - kubernetes.io/pvc-protection  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem